Fixed linter warning (#549)
## Issue
```
  Error: /home/runner/work/cbuild/cbuild/pkg/utils/exec.go:58:36: G115: integer overflow conversion uintptr -> int (gosec)
  			w, h, ptyErr := term.GetSize(int(os.Stdout.Fd()))
  			                                ^
  Error: /home/runner/work/cbuild/cbuild/pkg/utils/west.go:264:30: G703: Path traversal via taint analysis (gosec)
  		} else if _, err := os.Stat(value); os.IsNotExist(err) {
```

## Changes
- Suppressing the warning as the recent linter specifications are too
strict and not relevant in our case

## Checklist
<!-- Put an `x` in the boxes. All tasks must be completed and boxes
checked before merging. -->
- [ ] 🤖 This change is covered by unit tests (if applicable).
- [x] 🤹 Manual testing has been performed (if necessary).
- [ ] 🛡️ Security impacts have been considered (if relevant).
- [ ] 📖 Documentation updates are complete (if required).
- [ ] 🧠 Third-party dependencies and TPIP updated (if required).